###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/10

###
DELETE http://localhost:3001/api/persons/6317b76be942cfd94a74b6e

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "new person from vscode",
  "number": "123-456-7890"
}
